services:

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: todolist_db
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      MYSQLHOST: db
      MYSQLPORT: 3306
      MYSQLDATABASE: todolist_db
      MYSQLUSER: root
      MYSQLPASSWORD: root
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
